[package]
name = "nightcycle/package"
description = "A package!"
version = "1.0.0"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
HashUtil = "boatbomber/hashlib@1.0.0"
TestEZ = "roblox/testez@0.4.1"
TableUtil = "nightcycle/table-util@1.1.0"