[package]
name = "nightcycle/serializer"
description = "Serialized mixed tables of roblox data types and instances into a JSON encodable table."
version = "0.1.10"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
# Serialize = "sleitnick/ser@^1.0.5"